name: Release and Publish

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      NPM_CONFIG_PROVENANCE: true
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cache node_modules to prevent redundant installs
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: 📥 Install dependencies
        run: npm install --legacy-peer-deps

  release:
    needs: setup  # Ensure that the release job waits for the setup job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      NPM_CONFIG_PROVENANCE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      # Restore cache from the setup job (node_modules and Nx dependencies)
      - name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Verify Nx Installation
        run: npx nx --version

      - name: Build affected modules
        run: npx nx affected -t build

      - name: Print Environment Info
        run: npx nx report

      - name: 🚀 Release
        run: npx nx release --skip-publish

      - name: 🚀 Publish packages
        run: npx nx release publish --access=public
