# Name of your workflow
name: Release

# Rules that trigger the workflow
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Verify Nx Installation
        run: npx nx --version

      - name: Run nx release
        run: npm run release

      - name: Enable Debug Info (optional)
        run: echo "NODE_DEBUG=fs,module,timers" >> $GITHUB_ENV
