# Name of your workflow
name: Release

# Rules that trigger the workflow
on:
  push:
    branches:
      - main
env:
  # NX release needs to have a GH token in env.GITHUB_TOKEN
  # As during this workflow we will create a new release
  # that should trigger other workflow, we need to create custom TOKEN
  # with proper permissions,
  # more: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        # Only a single commit is fetched by default
        # we need full repo history with tags, so we are setting fetch-depth: 0
        with:
          fetch-depth: 0
          # We need to pass Personal Access Token in order
          # to force triggering on-publish workflow
          token: ${{ secrets.PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Sets the base and head SHAs for the nx affected commands in CI
        uses: nrwl/nx-set-shas@v4

      - name: Run nx release
        run: npm run release
