name: Release and Publish

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  NODE_AUTH_TOKEN: ${{ secrets.PAT }}
  NPM_CONFIG_PROVENANCE: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cache the node_modules folder and other important build files
      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            dist  # Add more paths as needed
          key: ${{ runner.os }}-workspace-${{ hashFiles('package-lock.json') }}

      - name: 📥 Install deps
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

  release:
    needs: setup  # Depends on the setup job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Restore cache from the setup job (node_modules and build files)
      - name: Restore workspace cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            dist
          key: ${{ runner.os }}-workspace-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-workspace-

      - name: Verify Nx Installation
        run: npx nx --version

      - name: 🚀 Release
        run: npx nx release --skip-publish

  publish:
    needs: setup  # Depends on the setup job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Restore cache from the setup job (node_modules and build files)
      - name: Restore workspace cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            dist
          key: ${{ runner.os }}-workspace-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-workspace-

      - name: Print Environment Info
        run: npx nx report

      - name: 🚀 Publish
        run: npx nx release publish
